"""Rebuild ``src/docfill/data/ro_localities.txt`` from the SIRUTA data of ``django-siruta``.

SIRUTA is the official register of the localities of Romania (Institutul Național de
Statistică). The ``django-siruta`` package (BSD 2-Clause) republishes its names per county, in
capitals and with the legacy cedilla letters; this script turns them into the spelling of the
identity card (capitalised words, comma-below ș / ț) and keeps one name per line, grouped by
the county code the card prints (``Jud.CJ``) and typed the way the card does: ``M`` for a
municipality (``Mun.``), ``O`` for a town (``Oraș``), ``C`` for a commune (``Com.``) and ``S``
for a locality of a commune (``Sat``).

    pip download django-siruta==0.3.0 --no-deps -d /tmp/siruta
    python tools/build_localities.py /tmp/siruta/django_siruta-0.3.0-py3-none-any.whl
"""

from __future__ import annotations

import ast
import re
import sys
import unicodedata
import zipfile
from pathlib import Path

OUTPUT = Path(__file__).resolve().parents[1] / "src" / "docfill" / "data" / "ro_localities.txt"
_CEDILLA = str.maketrans("ŞşŢţ", "ȘșȚț")
# Words written in lower case inside a name: "Valea lui Mihai", "Băița de sub Codru".
_SMALL = {"de", "din", "lui", "la", "sub", "pe", "cu", "cel", "în", "al"}
_ROMAN = {"i", "ii", "iii", "iv"}  # "Gersa II"; not "vii" (vineyards: "Apele Vii")

HEADER = """\
# Localities of Romania by county, one per line under the county code printed on identity
# cards ("Jud.CJ"). Generated by tools/build_localities.py: do not edit by hand.
#
# Source: SIRUTA, the official register of the administrative-territorial units, as published
# by the django-siruta package (https://github.com/ionelmc/django-siruta).
#
# BSD 2-Clause License
# Copyright (c) 2025, Ionel Cristian Mărieș. All rights reserved.
# Redistribution and use in source and binary forms, with or without modification, are
# permitted provided that the following conditions are met:
#   1. Redistributions of source code must retain the above copyright notice, this list of
#      conditions and the following disclaimer.
#   2. Redistributions in binary form must reproduce the above copyright notice, this list of
#      conditions and the following disclaimer in the documentation and/or other materials
#      provided with the distribution.
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
# EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
# TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""


def _word(word: str, first: bool) -> str:
    low = word.lower()
    if not first and low in _SMALL:
        return low
    if low in _ROMAN:
        return word.upper()
    if re.fullmatch(r"(?:[a-zăâîșț]\.)+", low):  # the initials of "I.C.BRĂTIANU", "C.A. ROSETTI"
        return word.upper()
    return word[:1].upper() + word[1:].lower()


def title(name: str) -> str:
    """``VALEA LUI MIHAI`` -> ``Valea lui Mihai``, ``TÂRGU MUREŞ`` -> ``Târgu Mureș``."""
    name = name.translate(_CEDILLA).strip()
    name = re.sub(r"\.(?=[^\s.])", ". ", name)  # "I.C.BRĂTIANU" -> "I. C. BRĂTIANU"
    name = re.sub(r"\s+", " ", name)
    parts = re.split(r"( |-)", name)
    words = [part for part in parts if part not in (" ", "-")]
    out, index = [], 0
    for part in parts:
        if part in (" ", "-"):
            out.append(part)
            continue
        out.append(_word(part, first=index == 0))
        index += 1
    assert len(words) == index
    return "".join(out)


def _plain(name: str) -> str:
    decomposed = unicodedata.normalize("NFD", name)
    stripped = "".join(char for char in decomposed if unicodedata.category(char) != "Mn")
    return re.sub(r"[\s\-]+", " ", stripped.casefold())


def _marks(name: str) -> int:
    return sum(char in "ăâîșțĂÂÎȘȚ" for char in name)


def _consistent(units: dict[str, set[str]]) -> None:
    """The register spells some names two ways inside a county, without a diacritic in one place
    ("Stefănești" for the town, "Ștefănești" for its locality): the spelling with the most
    diacritics is used for both, the commune or town's before the locality's when it is a tie."""
    best: dict[str, str] = {}
    for kind in "MOCS":  # the units of a county come before their localities
        for name in sorted(units[kind]):
            key = _plain(name)
            if key not in best or _marks(name) > _marks(best[key]):
                best[key] = name
    for kind in units:
        units[kind] = {best[_plain(name)] for name in units[kind]}


def _load(wheel: Path) -> dict:
    with zipfile.ZipFile(wheel) as archive:
        source = archive.read("siruta/data.py").decode("utf8")
    values: dict = {}
    for node in ast.parse(source).body:  # plain assignments of literals: nothing is executed
        if isinstance(node, ast.Assign) and isinstance(node.value, ast.Dict):
            values[node.targets[0].id] = ast.literal_eval(node.value)
    return values


_PARENT = re.compile(r"^\s*(\d+):\s*(\d+),\s*#\s*(.*?)\s*->\s*(.*?)\s*$", re.MULTILINE)


def _parents(source: str) -> list[tuple[int, str]]:
    """``(code of the first locality, name)`` of every commune, town and municipality: the data
    lists the localities only, and names the units that contain them in a comment."""
    tail = source[source.index("LOCALITY_ALIASES") :]
    return [(int(match[2]), match[3]) for match in _PARENT.finditer(tail)]


def build(wheel: Path) -> str:
    with zipfile.ZipFile(wheel) as archive:
        source = archive.read("siruta/data.py").decode("utf8")
    data = _load(wheel)
    code_by_id = {county_id: code for code, county_id in data["COUNTY_IDS_BY_CODE"].items()}
    county_of: dict[int, int] = {}  # SIRUTA code of a locality -> county
    units: dict[int, dict[str, set[str]]] = {}
    for county_id, localities in data["LOCALITIES_BY_COUNTY_ID"].items():
        units[county_id] = {"M": set(), "O": set(), "C": set(), "S": set()}
        for siruta, name in localities.items():
            county_of[siruta] = county_id
            if not name.startswith("BUCUREŞTI SECTORUL"):  # the card prints "Mun.București Sec.2"
                units[county_id]["S"].add(title(name))
    for first_child, name in _parents(source):
        kind, bare = "C", name
        for prefix, letter in (("MUNICIPIUL ", "M"), ("ORAŞ ", "O")):
            if name.startswith(prefix):
                kind, bare = letter, name[len(prefix) :]
        if first_child in county_of:
            units[county_of[first_child]][kind].add(title(bare))
    lines = [HEADER]
    for county_id in sorted(units, key=lambda i: code_by_id[i]):
        _consistent(units[county_id])
        lines.append(f"[{code_by_id[county_id]}]")
        for kind in "MOCS":
            names = units[county_id][kind]
            if code_by_id[county_id] == "B" and kind == "M":
                names = {"București"}
            lines.extend(f"{kind} {name}" for name in sorted(names, key=str.casefold))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    OUTPUT.write_text(build(Path(sys.argv[1])), encoding="utf8")
    print(f"wrote {OUTPUT}")
