"""Catalog of the fields docfill knows.

Each field has a kind (which drives validation and normalisation), a group (how the wizard
arranges it) and label synonyms. The label-based extractor picks up synonyms automatically and
standard documents reference fields as ``{{ name }}``. Synonyms are matched case- and
accent-insensitively ("Județ" == "judet"); multilingual labels printed on identity cards such as
``Nume/Nom/Last name`` match through any of their parts.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

FieldKind = Literal[
    "name",
    "address",
    "place",
    "postal_code",
    "country",
    "text",
    "cnp",
    "date",
    "sex",
    "email",
    "phone",
    "iban",
    "id_series",
    "id_number",
    "short",
    "code",
    "checkbox",
    "list",
]

GROUPS = {
    "person": "Person",
    "birth": "Birth",
    "domicile": "Domicile",
    "id_card": "Identity card",
    "parents": "Parents",
    "company": "Company",
    "filing": "Request",
    "contact": "Contact person",
    "billing": "Billing",
    "filer": "Filed by",
    "other": "Other",
}


@dataclass(frozen=True)
class FieldSpec:
    name: str
    label: str
    kind: FieldKind
    synonyms: tuple[str, ...] = ()
    group: str = "other"
    max_length: int = 120


def _f(name, label, kind, group, synonyms=(), max_length=120) -> FieldSpec:
    return FieldSpec(name, label, kind, tuple(synonyms), group, max_length)


_SPECS = [
    # ---------------------------------------------------------------- person
    _f(
        "last_name",
        "Last name (Nume)",
        "name",
        "person",
        (
            "last name",
            "surname",
            "family name",
            "nom",
            "nume",
            "numele",
            "nume de familie",
            "numele de familie",
        ),
        80,
    ),
    _f(
        "first_name",
        "First name (Prenume)",
        "name",
        "person",
        (
            "first name",
            "first names",
            "given name",
            "given names",
            "forename",
            "forenames",
            "christian name",
            "prenom",
            "prenume",
            "prenumele",
        ),
        80,
    ),
    _f(
        "full_name",
        "Full name",
        "name",
        "person",
        (
            "full name",
            "name",
            "name and surname",
            "applicant",
            "applicant name",
            "holder",
            "holder name",
            "nume si prenume",
            "numele si prenumele",
            "nume complet",
            "subsemnatul",
            "subsemnata",
            "subsemnatul(a)",
        ),
    ),
    _f(
        "cnp",
        "CNP",
        "cnp",
        "person",
        (
            "cnp",
            "cnp/nif",
            "cod numeric personal",
            "codul numeric personal",
            "personal numeric code",
            "personal code",
        ),
        20,
    ),
    _f("sex", "Sex", "sex", "person", ("sex", "sexul", "sexe", "gender"), 12),
    _f(
        "citizenship",
        "Citizenship (Cetățenia)",
        "text",
        "person",
        (
            "cetatenia",
            "cetatenie",
            "nationality",
            "nationalite",
            "citizenship",
        ),
        40,
    ),
    # ---------------------------------------------------------------- birth
    _f(
        "date_of_birth",
        "Date of birth",
        "date",
        "birth",
        (
            "date of birth",
            "birth date",
            "data nasterii",
            "data de nastere",
            "nascut la data",
            "date de naissance",
        ),
        30,
    ),
    _f(
        "place_of_birth",
        "Place of birth",
        "place",
        "birth",
        (
            "place of birth",
            "birthplace",
            "birth place",
            "city of birth",
            "locul nasterii",
            "loc nastere",
            "locul de nastere",
            "lieu de naissance",
            "nascut in localitatea",
            "nascut(a) in localitatea",
        ),
    ),
    _f(
        "birth_county",
        "County of birth",
        "place",
        "birth",
        (
            "judetul nasterii",
            "judet nastere",
        ),
        60,
    ),
    _f(
        "birth_country",
        "Country of birth",
        "country",
        "birth",
        (
            "tara nasterii",
            "country of birth",
        ),
        60,
    ),
    # ---------------------------------------------------------------- parents
    _f(
        "father_last_name",
        "Father's last name",
        "name",
        "parents",
        (
            "numele de familie al tatalui",
            "nume tata",
        ),
        80,
    ),
    _f(
        "father_first_name",
        "Father's first name",
        "name",
        "parents",
        (
            "prenumele tatalui",
            "prenume tata",
        ),
        80,
    ),
    _f(
        "mother_last_name",
        "Mother's last name",
        "name",
        "parents",
        (
            "numele de familie al mamei",
            "nume mama",
        ),
        80,
    ),
    _f(
        "mother_first_name",
        "Mother's first name",
        "name",
        "parents",
        (
            "prenumele mamei",
            "prenume mama",
        ),
        80,
    ),
    # ---------------------------------------------------------------- domicile
    _f(
        "full_address",
        "Address",
        "address",
        "domicile",
        (
            "address",
            "home address",
            "residential address",
            "permanent address",
            "address of residence",
            "place of residence",
            "residence",
            "domicile",
            "adresse",
            "adresa",
            "adresa de domiciliu",
            "domiciliu",
            "domiciliul",
            "domiciliat in",
            "domiciliata in",
            "resedinta",
        ),
        250,
    ),
    _f(
        "street_address",
        "Street line",
        "address",
        "domicile",
        (
            "street address",
            "address line 1",
            "address line",
        ),
        150,
    ),
    _f("street", "Street (Strada)", "place", "domicile", ("street", "strada"), 100),
    _f(
        "street_number",
        "Number (Nr.)",
        "short",
        "domicile",
        (
            "street number",
            "house number",
            "numar strada",
        ),
        12,
    ),
    _f("building", "Block (Bloc)", "short", "domicile", ("bloc", "building", "block"), 12),
    _f("entrance", "Staircase (Scara)", "short", "domicile", ("scara", "staircase"), 12),
    _f("floor", "Floor (Etaj)", "short", "domicile", ("etaj", "floor"), 12),
    _f(
        "apartment",
        "Apartment (Ap.)",
        "short",
        "domicile",
        (
            "apartament",
            "apartment",
            "flat",
        ),
        12,
    ),
    _f(
        "city",
        "City / locality",
        "place",
        "domicile",
        (
            "city",
            "town",
            "city/town",
            "locality",
            "municipality",
            "village",
            "oras",
            "orasul",
            "localitate",
            "localitatea",
            "municipiul",
            "comuna",
            "domiciliat in localitatea",
            "domiciliat(a) in localitatea",
        ),
        80,
    ),
    _f(
        "postal_code",
        "Postal code",
        "postal_code",
        "domicile",
        (
            "postal code",
            "postcode",
            "post code",
            "zip",
            "zip code",
            "zipcode",
            "cod postal",
        ),
        12,
    ),
    _f(
        "region",
        "County / sector (Județ)",
        "place",
        "domicile",
        (
            "state",
            "county",
            "province",
            "region",
            "state/province",
            "judet",
            "judetul",
            "judet/sector",
            "sector",
        ),
        80,
    ),
    _f(
        "country",
        "Country (Țara)",
        "country",
        "domicile",
        (
            "country",
            "country of residence",
            "tara",
            "tara de resedinta",
        ),
        80,
    ),
    # ---------------------------------------------------------------- identity card
    _f(
        "id_type",
        "ID document type",
        "short",
        "id_card",
        (
            "act identitate",
            "act de identitate",
            "tip act",
            "tipul actului",
            "document type",
        ),
        20,
    ),
    _f("id_series", "ID series (Seria)", "id_series", "id_card", ("seria", "serie", "series"), 4),
    _f(
        "id_number",
        "ID number (Nr.)",
        "id_number",
        "id_card",
        (
            "numar act",
            "nr act",
            "document number",
            "numarul actului",
        ),
        12,
    ),
    _f(
        "id_issued_by",
        "ID issued by",
        "text",
        "id_card",
        (
            "emis de",
            "emisa de",
            "emis(a) de",
            "eliberat de",
            "eliberata de",
            "issued by",
            "delivree par",
            "emisa de/delivree par/issued by",
        ),
        80,
    ),
    _f(
        "id_issue_date",
        "ID issue date",
        "date",
        "id_card",
        (
            "data eliberarii",
            "eliberat la data",
            "emis la data",
            "date of issue",
            "issue date",
        ),
        30,
    ),
    _f(
        "id_expiry_date",
        "ID valid until",
        "date",
        "id_card",
        (
            "valabil pana la",
            "valabil pana la data",
            "date of expiry",
            "expiry date",
        ),
        30,
    ),
    # ---------------------------------------------------------------- company
    _f(
        "company_name",
        "Company name",
        "text",
        "company",
        (
            "denumire firma",
            "denumirea firmei",
            "pentru firma",
            "company name",
        ),
        150,
    ),
    _f(
        "company_address",
        "Registered office (full)",
        "address",
        "company",
        (
            "sediul social",
            "sediu social",
            "sediul social in",
            "registered office",
        ),
        250,
    ),
    _f("company_city", "Registered office: locality", "place", "company", (), 80),
    _f("company_street", "Registered office: street", "place", "company", (), 100),
    _f("company_street_number", "Registered office: number", "short", "company", (), 12),
    _f("company_building", "Registered office: block", "short", "company", (), 12),
    _f("company_entrance", "Registered office: staircase", "short", "company", (), 12),
    _f("company_floor", "Registered office: floor", "short", "company", (), 12),
    _f("company_apartment", "Registered office: apartment / room", "short", "company", (), 20),
    _f("company_county", "Registered office: county / sector", "place", "company", (), 60),
    _f("company_email", "Company e-mail", "email", "company", (), 120),
    _f("company_phone", "Company phone", "phone", "company", (), 30),
    _f("company_website", "Company website", "text", "company", (), 120),
    _f(
        "company_registration_number",
        "Trade register number",
        "short",
        "company",
        (
            "numar de ordine in registrul comertului",
            "nr. de ordine",
            "registration number",
        ),
        30,
    ),
    _f(
        "company_cui",
        "CUI (fiscal code)",
        "short",
        "company",
        (
            "cui",
            "cod unic de inregistrare",
            "cif",
            "cod fiscal",
            "vat number",
        ),
        20,
    ),
    _f(
        "caen_activities",
        "CAEN activities at the registered office (one per line: code name)",
        "list",
        "company",
        (),
        4000,
    ),
    _f(
        "caen_third_party",
        "CAEN activities at third parties (one per line: code name)",
        "list",
        "company",
        (),
        4000,
    ),
    # ---------------------------------------------------------------- request / filing
    _f(
        "orc_office",
        "Trade register office (tribunal)",
        "place",
        "filing",
        ("oficiul registrului comertului de pe langa tribunalul",),
        60,
    ),
    _f("request_registration", "Request: înmatriculare (registration)", "checkbox", "filing"),
    _f("request_object", "Subject of the request", "text", "filing", ("obiectul cererii",), 150),
    _f("request_communication", "Request: communication of the documents", "checkbox", "filing"),
    _f(
        "communication_method",
        "Communication by (poștă / curier / mijloace electronice / sediul O.R.C.T.)",
        "text",
        "filing",
        (),
        40,
    ),
    _f(
        "capacity",
        "Signs in the capacity of",
        "text",
        "filing",
        (
            "in calitate de",
            "calitate",
        ),
        120,
    ),
    _f("represented_by", "Represented by (prin)", "text", "filing", (), 120),
    _f("representation_basis", "Based on (conform)", "text", "filing", (), 150),
    _f(
        "marital_regime",
        "Marital regime",
        "text",
        "filing",
        (
            "regimul matrimonial",
            "regim matrimonial",
        ),
        80,
    ),
    _f(
        "request_operating_declaration",
        "Request 4.3: sworn statement on operating conditions (Anexa 4)",
        "checkbox",
        "filing",
    ),
    _f("annex_numbers", "Annexes that are part of the request (e.g. 4)", "short", "filing", (), 30),
    _f(
        "attached_documents",
        "Documents submitted (one per line: name | number/date | pages)",
        "list",
        "filing",
        (),
        4000,
    ),
    _f("attached_pages_total", "Total pages submitted", "short", "filing", (), 10),
    # ---------------------------------------------------------------- filed by (XII)
    _f("filer_last_name", "Filed by: last name", "name", "filer", (), 80),
    _f("filer_first_name", "Filed by: first name", "name", "filer", (), 80),
    _f("filer_id_type", "Filed by: ID document type", "short", "filer", (), 20),
    _f("filer_id_series", "Filed by: ID series", "id_series", "filer", (), 4),
    _f("filer_id_number", "Filed by: ID number", "id_number", "filer", (), 12),
    _f("filer_cnp", "Filed by: CNP", "cnp", "filer", (), 20),
    _f("filer_capacity", "Filed by: capacity (e.g. avocat)", "text", "filer", (), 80),
    _f("filer_basis", "Filed by: based on (conform)", "text", "filer", (), 120),
    _f("filer_basis_number", "Filed by: document number", "short", "filer", (), 30),
    _f("filer_basis_date", "Filed by: document date", "date", "filer", (), 30),
    # ---------------------------------------------------------------- contact person (VII)
    _f("contact_last_name", "Contact: last name", "name", "contact", (), 80),
    _f("contact_first_name", "Contact: first name", "name", "contact", (), 80),
    _f("contact_city", "Contact: locality", "place", "contact", (), 80),
    _f("contact_street", "Contact: street", "place", "contact", (), 100),
    _f("contact_street_number", "Contact: number", "short", "contact", (), 12),
    _f("contact_building", "Contact: block", "short", "contact", (), 12),
    _f("contact_entrance", "Contact: staircase", "short", "contact", (), 12),
    _f("contact_floor", "Contact: floor", "short", "contact", (), 12),
    _f("contact_apartment", "Contact: apartment", "short", "contact", (), 12),
    _f("contact_county", "Contact: county / sector", "place", "contact", (), 60),
    _f("contact_postal_code", "Contact: postal code", "postal_code", "contact", (), 12),
    _f("contact_phone", "Contact: phone", "phone", "contact", (), 30),
    _f("contact_email", "Contact: e-mail", "email", "contact", (), 120),
    # ---------------------------------------------------------------- billing (VIII)
    _f("billing_name", "Billing: name / company", "text", "billing", (), 150),
    _f("billing_code", "Billing: CNP / CUI", "short", "billing", (), 20),
    _f("billing_email", "Billing: e-mail", "email", "billing", (), 120),
    _f("billing_bank", "Billing: bank", "text", "billing", (), 80),
    _f("billing_iban", "Billing: IBAN", "iban", "billing", (), 40),
    _f("billing_address", "Billing: registered office / address", "address", "billing", (), 250),
    # ---------------------------------------------------------------- general contact
    _f("email", "E-mail", "email", "person", ("e-mail", "email", "adresa de e-mail"), 120),
    _f("phone", "Phone", "phone", "person", ("telefon", "tel", "phone", "mobile"), 30),
]

FIELDS: dict[str, FieldSpec] = {spec.name: spec for spec in _SPECS}

# Labels that only mean something on one kind of document (checked before general synonyms).
TYPE_SYNONYMS: dict[str, dict[str, str]] = {
    "birth_certificate": {
        "judetul": "birth_county",
        "comuna": "place_of_birth",
        "orasul": "place_of_birth",
        "municipiul": "place_of_birth",
        "comuna/orasul/municipiul": "place_of_birth",
        "orasul/municipiul": "place_of_birth",
        "sexul": "sex",
    },
    "id_card": {
        "loc nastere": "place_of_birth",
        "domiciliu": "full_address",
    },
}


def field_labels() -> dict[str, str]:
    return {name: spec.label for name, spec in FIELDS.items()}
